# moving doesn't work, but gives focus somehow (?)
windowrule {
  name = "Configure ModernGL"
  match:class = ModernGL
  float = on
  center = true
}

# windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
